INSERT INTO PROGRAMS(Major)
VALUES('Business');
INSERT INTO PROGRAMS
VALUES('Animal Science/Pre-Vet');
INSERT INTO PROGRAMS
VALUES('Education');
INSERT INTO PROGRAMS
VALUES('Equestrian');
INSERT INTO PROGRAMS
VALUES('Physician Assistant');
INSERT INTO PROGRAMS
VALUES('Pharmacy');


